<a href="https://colab.research.google.com/github/Harshita0201/Machine_Learning/blob/main/DL_1_artificial_neural_network(CLASSIFICATION).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [ ]:
tf.__version__

'2.12.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values  #iloc[rowrange, colrange], we are leaving first three cols of dataset (ronum, cusId, surname) as they do not have any impact on our output
y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [ ]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data (dependent variables)




Label Encoding the "Gender" column

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2]) #we want to apply it to all rows and 2 col that is gender col of dataset

In [ ]:
print(X[:, 2])

[0 0 0 ... 0 1 0]


In [ ]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


so female got encodes as '0' and males as '1'

One Hot Encoding the "Geography" column

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers= [('encoder', OneHotEncoder(), [1])], remainder='passthrough') #col at index 1 is geo col that needs to be transformed
X= np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


After transformation the 1 col shits to 0 and it is encoded as - 1.0.0 -french, 0.0.1-Germany...

### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

### Feature Scaling

scaling all the features including the dummy variables

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
#create a variable that will initialise the model, which is going to be object of Sequential class of models under keras library of tensorflow
ann = tf.keras.models.Sequential()
# then further sequence of layers of artificial neural network are built on this object ann

### Adding the input layer and the first hidden layer

In [ ]:
#using dense method
# Sequential class has add method to ass layers
ann.add(tf.keras.layers.Dense(units=6, activation ='relu')) # to add fully connected layer as an object of dense class 
#imp parasms of Dense() class- 1.Units = number os neurons of our layer 2. activation func(here we are using rectifier)

### Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation ='relu'))

### Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1, activation ='sigmoid')) # the output neuron is just one (acc to dataset outout is 1 or 0) customer leaves or stays and activation funct is sigmoid (it will tell us the probability of leaving and staying)


## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
ann.compile(optimizer= 'adam', loss='binary_crossentropy', metrics=['accuracy']) #param1= optimiser(we used to adjiust weights) #param2=how we are caluculating loss #param3=metrics : how we calculate accuracy
#adam optimizer -> stochastic gradient descent
#for binary classification (0, 1 prediction) models we use loss func binary_crossentropy
#for categorical classification (0, 1, 2 prediction) models we use loss func categorical_crossentropy

### Training the ANN on the Training set

In [ ]:
ann.fit(X_train, y_train, batch_size=32, epochs=100) #batch learning over 100 iterations

Epoch 1/100
250/250 [==============================] - 2s 2ms/step - loss: 0.5510 - accuracy: 0.7496
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4699 - accuracy: 0.7994
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4383 - accuracy: 0.8083
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4218 - accuracy: 0.8158
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4094 - accuracy: 0.8206
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3945 - accuracy: 0.8326
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3815 - accuracy: 0.8380
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3724 - accuracy: 0.8403
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3650 - accuracy: 0.8436
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3608 - accura

Training accuracy of 86.33%

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

**Solution**

In [ ]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000 ]]))>0.5) #since we scaled the features while training therefore we need to scale these features for predict method(same as training scaling)
#we put a >0.5 to set a threshold if the value is above 0.5 then it is true, else false

1/1 [==============================] - 0s 26ms/step
[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5) #convert them into boolean value 
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test), 1)), 1))


63/63 [==============================] - 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm= confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)*100

[[1584   11]
 [ 330   75]]


82.95