<a href="https://colab.research.google.com/github/Harshita0201/Machine_Learning/blob/main/DL_2_artificial_neural_network(regression).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [3]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [4]:
tf.__version__

'2.12.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [5]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [6]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [7]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

## Part 2 - Building the ANN

### Initializing the ANN

In [9]:
#initialising ann object of Sequential class
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [10]:
ann.add(tf.keras.layers.Dense(units = '6', activation = 'relu')) 
#units- number of neurons, and linear rectifier as our activation func
#units in first layer is automatically picked, but we set neurons for hidden layer (here we choose 6)

### Adding the second hidden layer

In [11]:
ann.add(tf.keras.layers.Dense(units = '6', activation = 'relu'))  #number of neurons in second hidden layer same as previous

### Adding the output layer

In [12]:
#there is going to be one output neuron only (that will show the regression result (continuous value)) therefore no activation function required here
ann.add(tf.keras.layers.Dense(units = '1')) 

## Part 3 - Training the ANN

### Compiling the ANN

In [13]:
#during compilation we use adam optimiser for refitting the weights (stochastic gradient descent)-used for both classification and regression
# and loss function for regression is mean squared error
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [14]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
240/240 [==============================] - 2s 2ms/step - loss: 2430.3350
Epoch 2/100
240/240 [==============================] - 0s 2ms/step - loss: 345.3046
Epoch 3/100
240/240 [==============================] - 0s 2ms/step - loss: 323.5359
Epoch 4/100
240/240 [==============================] - 0s 2ms/step - loss: 298.8324
Epoch 5/100
240/240 [==============================] - 0s 2ms/step - loss: 272.4546
Epoch 6/100
240/240 [==============================] - 0s 2ms/step - loss: 244.5643
Epoch 7/100
240/240 [==============================] - 0s 2ms/step - loss: 217.0730
Epoch 8/100
240/240 [==============================] - 0s 2ms/step - loss: 188.3830
Epoch 9/100
240/240 [==============================] - 0s 2ms/step - loss: 159.6196
Epoch 10/100
240/240 [==============================] - 0s 2ms/step - loss: 132.5506
Epoch 11/100
240/240 [==============================] - 0s 2ms/step - loss: 107.8311
Epoch 12/100
240/240 [==============================] - 1s 2ms/step - los

Epoch — One epoch is when the entire dataset is passed through the network once. This comprises of one instance of a forward pass and back-propagation.

The batch size is a number of samples processed before the model is updated. The number of epochs is the number of complete passes through the training dataset. The size of a batch must be more than or equal to one and less than or equal to the number of samples in the training dataset

### Predicting the results of the Test set

In [16]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))


60/60 [==============================] - 0s 2ms/step
[[431.51 431.23]
 [462.6  460.01]
 [466.09 461.14]
 ...
 [473.34 473.26]
 [440.11 438.  ]
 [459.34 463.28]]
